version: '3.8'

services:
  bits-and-bytes-bot:
    build: .
    depends_on:
      - postgres
    env_file: ./.env
    environment:
      POSTGRES_URI: postgres
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: bitsAndBytes
      POSTGRES_USER: bitsAndBytes
      POSTGRES_PASSWORD: AVeryLongAndSecurePassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
